apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demoApp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demoApp
    spec:
      containers:
      - name: demoApp
        image: ramkitcs/dockerapp:32
        ports:
        - containerPort: 80


